[package]
name = "default"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.66", features = ["backtrace"] }
prost = "0.11"
tensorflow = { version = "0.19.1", features = ["eager", "tensorflow_gpu"] }
tfprotos-config = { path = "." }

[[bin]]
name = "main"
